### Get latest commits

POST https://api.github.com/graphql
Accept: application/vnd.github+json
Authorization: Bearer ghp_ABC1234
X-Request-Type: GraphQL

query LatestChanges($owner: String!, $repository: String!, $after: String) {
  repository(owner: $owner, name: $repository) {
    nameWithOwner
    defaultBranchRef {
      target {
        ... on Commit {
          history(first: 20 after: $after) {
            pageInfo {
              endCursor
            }
            edges {
              node {
                ... on Commit {
                  abbreviatedOid
                  committedDate
                  url
                  associatedPullRequests(first: 1) {
                    nodes {
                      number
                      url
                      title
                      body
                      isDraft
                      createdAt
                      additions
                      changedFiles
                      deletions
                      totalCommentsCount
                      author {
                        login
                        url
                        ... on User {
                          name
                          organizations(first: 3) {
                            nodes {
                              name
                            }
                          }
                        }
                      }
                      latestReviews(first: 5) {
                        totalCount
                        nodes {
                          author {
                            login
                            url
                            ... on User {
                              name
                            }
                          }
                        }
                      }
                      closingIssuesReferences(first: 1) {
                        nodes {
                          url
                          title
                          labels(first: 5) {
                            nodes {
                              name
                              url
                            }
                          }
                          reactions {
                            totalCount
                          }
                        }
                      }
                      reactions {
                        totalCount
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

### Open pull requests

POST https://api.github.com/graphql
Accept: application/vnd.github+json
Authorization: Bearer ghp_ABC1234
X-Request-Type: GraphQL

query OpenPulls($owner: String!, $repository: String!, $after: String) {
  repository(owner: $owner, name: $repository) {
    pullRequests(states: [OPEN] first: 25 after: $after) {
      pageInfo {
        endCursor
        hasNextPage
      }
      nodes {
        number
        url
        title
        body
        isDraft
        createdAt
        additions
        changedFiles
        deletions
        totalCommentsCount
        author {
          login
          url
          ... on User {
            name
          }
        }
        latestReviews(first: 10) {
          totalCount
          nodes {
            author {
              login
              url
              ... on User {
                name
              }
            }
          }
        }
        reactions {
          totalCount
        }
        reviewRequests(first: 10) {
          totalCount
          nodes {
            author: requestedReviewer {
              ... on User {
                login
                url
                name
              }
            }
          }
        }
      }
    }
  }
}
